/**
 * ace#1821 — the pool planner behind `/ace:mobile-bootstrap --pool N`.
 *
 * Two controls run against the DEFECT, not just the new code:
 *
 *   1. `commands/mobile-bootstrap.md` must document a `--pool` mode. Pre-fix,
 *      that file says "Confirm `${ACE_AVD_NAME}` … **exists**" — singular — and
 *      nothing in the repo ever creates a second AVD, which is the entire
 *      reason `selectAvd`'s fallback branch has never fired in production.
 *      This case fails on `origin/main`.
 *   2. The tuned-key delta computed from a real `avdmanager`-default config
 *      against the reference host's PROVEN config must be non-empty and must
 *      name the profile keys (RAM, data partition, GPU, heap). A planner that
 *      returned `[]` here would create pool members on a stock Pixel-7 profile
 *      and read as working.
 *
 * Both fixtures below are verbatim excerpts: `PROVEN_INI` from
 * `~/.android/avd/ACE_Pixel_API_34.avd/config.ini` on the reference host
 * (2026-09-05), `STOCK_INI` from the `avdmanager create avd -d pixel_7`
 * defaults for the same system image.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  MAX_POOL_SIZE,
  applyTunedConfigDelta,
  createAvdCommand,
  isTunedConfigKey,
  parseConfigIni,
  planAvdPool,
  poolMemberNames,
  systemImagePackageFromSysdir,
  tunedConfigDelta,
} from '../../lib/avd-pool-plan.js';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');

/** Reference host's tuned AVD (excerpt — the tuned keys plus identity keys). */
const PROVEN_INI = [
  'AvdId=ACE_Pixel_API_34',
  'abi.type=arm64-v8a',
  'avd.ini.displayname=ACE Pixel API 34',
  'disk.dataPartition.size=6G',
  'hw.camera.back=emulated',
  'hw.camera.back.orientation=90',
  'hw.camera.front=emulated',
  'hw.camera.front.orientation=90',
  'hw.gpu.enabled=no',
  'hw.gpu.mode=auto',
  'hw.keyboard=no',
  'hw.keyboard.charmap=qwerty2',
  'hw.lcd.density=420',
  'hw.lcd.height=2400',
  'hw.lcd.width=1080',
  'hw.ramSize=2G',
  'image.sysdir.1=system-images/android-34/google_apis_playstore/arm64-v8a/',
  'path=/Users/someone/.android/avd/ACE_Pixel_API_34.avd',
  'sdcard.size=512M',
  'vm.heapSize=228M',
  '',
].join('\n');

/** What `avdmanager create avd -d pixel_7` writes before any tuning. */
const STOCK_INI = [
  '# generated by avdmanager',
  'AvdId=ACE_Pixel_API_34_b',
  'abi.type=arm64-v8a',
  'avd.ini.displayname=ACE_Pixel_API_34_b',
  'disk.dataPartition.size=2G',
  'hw.camera.back=emulated',
  'hw.camera.back.orientation=90',
  'hw.camera.front=none',
  'hw.gpu.enabled=yes',
  'hw.gpu.mode=host',
  'hw.keyboard=no',
  'hw.lcd.density=420',
  'hw.lcd.height=2400',
  'hw.lcd.width=1080',
  'hw.ramSize=1536',
  'image.sysdir.1=system-images/android-34/google_apis_playstore/arm64-v8a/',
  'path=/Users/someone/.android/avd/ACE_Pixel_API_34_b.avd',
  'vm.heapSize=228M',
  '',
].join('\n');

describe('CONTROL: the command documents a pool mode', () => {
  it('mobile-bootstrap.md offers `--pool N`, not just a singular existence check', () => {
    const md = readFileSync(join(REPO_ROOT, 'commands/mobile-bootstrap.md'), 'utf8');
    expect(md).toContain('--pool');
    // The whole defect in ace#1821 is that nothing ever CREATES a second AVD.
    expect(md).toMatch(/avdmanager create avd/);
  });
});

describe('poolMemberNames', () => {
  it('names member 1 as the bare base — existing machines are unchanged at the default size 1', () => {
    expect(poolMemberNames('ACE_Pixel_API_34', 1)).toEqual(['ACE_Pixel_API_34']);
  });

  it('suffixes members 2..N with _b, _c, …', () => {
    expect(poolMemberNames('ACE_Pixel_API_34', 3)).toEqual([
      'ACE_Pixel_API_34',
      'ACE_Pixel_API_34_b',
      'ACE_Pixel_API_34_c',
    ]);
  });

  it('rejects a size the naming scheme cannot express, instead of colliding names', () => {
    expect(() => poolMemberNames('X', MAX_POOL_SIZE + 1)).toThrow(/naming scheme/);
    expect(() => poolMemberNames('X', 0)).toThrow(/integer >= 1/);
    expect(() => poolMemberNames('  ', 2)).toThrow(/base AVD name/);
  });
});

describe('planAvdPool', () => {
  it('reports only the members that are actually missing', () => {
    const plan = planAvdPool('ACE_Pixel_API_34', 3, [
      'ACE_Pixel_API_34',
      'ACE_Pixel_API_34_b',
    ]);
    expect(plan.present).toEqual(['ACE_Pixel_API_34', 'ACE_Pixel_API_34_b']);
    expect(plan.missing).toEqual(['ACE_Pixel_API_34_c']);
  });

  it('is a no-op on a healthy pool — re-running --pool writes nothing', () => {
    const plan = planAvdPool('ACE_Pixel_API_34', 2, [
      'ACE_Pixel_API_34',
      'ACE_Pixel_API_34_b',
    ]);
    expect(plan.missing).toEqual([]);
  });

  it('ignores unrelated AVDs on the host rather than adopting them into the pool', () => {
    const plan = planAvdPool('ACE_Pixel_API_34', 2, [
      'Pixel_6_API_33',
      'ACE_Pixel_API_34_PS',
      'ACE_Pixel_API_34',
    ]);
    expect(plan.missing).toEqual(['ACE_Pixel_API_34_b']);
  });

  it('at the default size 1 the plan is empty on any machine that has bootstrapped', () => {
    expect(planAvdPool('ACE_Pixel_API_34', 1, ['ACE_Pixel_API_34']).missing).toEqual([]);
  });
});

describe('parseConfigIni', () => {
  it('keeps inner spacing in values — `512 MB` is a real avdmanager value', () => {
    expect(parseConfigIni('sdcard.size=512 MB\n')['sdcard.size']).toBe('512 MB');
  });

  it('drops comments and blank lines', () => {
    const parsed = parseConfigIni('# hi\n\nhw.ramSize=2G\n; also a comment\n');
    expect(parsed).toEqual({ 'hw.ramSize': '2G' });
  });
});

describe('isTunedConfigKey', () => {
  it('copies the profile keys', () => {
    for (const k of [
      'hw.ramSize',
      'disk.dataPartition.size',
      'vm.heapSize',
      'hw.gpu.mode',
      'hw.gpu.enabled',
      'hw.camera.front',
      'hw.camera.front.orientation',
      'hw.camera.back',
      'hw.lcd.density',
      'hw.keyboard',
      'hw.keyboard.charmap',
    ]) {
      expect(isTunedConfigKey(k), k).toBe(true);
    }
  });

  it('NEVER copies the clone-identity keys — copying `path` would point the clone at the reference AVD', () => {
    for (const k of ['AvdId', 'path', 'path.rel', 'avd.ini.displayname', 'image.sysdir.1']) {
      expect(isTunedConfigKey(k), k).toBe(false);
    }
  });
});

describe('CONTROL: tunedConfigDelta against a real stock-vs-proven pair', () => {
  const delta = tunedConfigDelta(PROVEN_INI, STOCK_INI);
  const byKey = Object.fromEntries(delta.map((d) => [d.key, d]));

  it('finds the profile drift a stock avdmanager clone actually has', () => {
    expect(delta.length).toBeGreaterThan(0);
    expect(byKey['hw.ramSize']).toEqual({ key: 'hw.ramSize', from: '1536', to: '2G' });
    expect(byKey['disk.dataPartition.size']).toEqual({
      key: 'disk.dataPartition.size',
      from: '2G',
      to: '6G',
    });
    expect(byKey['hw.gpu.enabled']).toEqual({ key: 'hw.gpu.enabled', from: 'yes', to: 'no' });
    expect(byKey['hw.gpu.mode']).toEqual({ key: 'hw.gpu.mode', from: 'host', to: 'auto' });
  });

  it('reports an ABSENT key as from:null rather than skipping it', () => {
    // avdmanager omits hw.camera.front.orientation and hw.keyboard.charmap.
    expect(byKey['hw.camera.front.orientation'].from).toBeNull();
    expect(byKey['hw.keyboard.charmap'].from).toBeNull();
  });

  it('never proposes writing an identity key', () => {
    for (const d of delta) {
      expect(['AvdId', 'path', 'avd.ini.displayname', 'image.sysdir.1']).not.toContain(d.key);
    }
  });

  it('leaves already-matching keys alone', () => {
    expect(byKey['vm.heapSize']).toBeUndefined();
    expect(byKey['hw.lcd.density']).toBeUndefined();
  });

  it('is empty when the clone already matches — idempotent re-runs', () => {
    expect(tunedConfigDelta(PROVEN_INI, PROVEN_INI)).toEqual([]);
  });
});

describe('applyTunedConfigDelta', () => {
  it('rewrites in place, appends what is absent, and preserves everything else', () => {
    const out = applyTunedConfigDelta(STOCK_INI, tunedConfigDelta(PROVEN_INI, STOCK_INI));
    const parsed = parseConfigIni(out);
    expect(parsed['hw.ramSize']).toBe('2G');
    expect(parsed['disk.dataPartition.size']).toBe('6G');
    expect(parsed['hw.camera.front']).toBe('emulated');
    expect(parsed['hw.camera.front.orientation']).toBe('90');
    // Identity survives untouched — this is the clone, not the reference.
    expect(parsed['AvdId']).toBe('ACE_Pixel_API_34_b');
    expect(parsed['path']).toBe('/Users/someone/.android/avd/ACE_Pixel_API_34_b.avd');
    expect(out).toContain('# generated by avdmanager');
  });

  it('applying twice is a fixed point', () => {
    const once = applyTunedConfigDelta(STOCK_INI, tunedConfigDelta(PROVEN_INI, STOCK_INI));
    const twice = applyTunedConfigDelta(once, tunedConfigDelta(PROVEN_INI, once));
    expect(twice).toBe(once);
  });

  it('returns the input untouched for an empty delta', () => {
    expect(applyTunedConfigDelta(STOCK_INI, [])).toBe(STOCK_INI);
  });
});

describe('systemImagePackageFromSysdir', () => {
  it('converts the reference host value verbatim', () => {
    expect(
      systemImagePackageFromSysdir('system-images/android-34/google_apis_playstore/arm64-v8a/'),
    ).toBe('system-images;android-34;google_apis_playstore;arm64-v8a');
  });

  it('returns null rather than a malformed -k argument', () => {
    expect(systemImagePackageFromSysdir('')).toBeNull();
    expect(systemImagePackageFromSysdir('android-34/google_apis/arm64-v8a/')).toBeNull();
    expect(systemImagePackageFromSysdir('system-images/android-34/')).toBeNull();
  });
});

describe('createAvdCommand', () => {
  it('quotes the package path — the semicolons would otherwise split the shell command', () => {
    expect(
      createAvdCommand('ACE_Pixel_API_34_b', 'system-images;android-34;google_apis_playstore;arm64-v8a'),
    ).toBe(
      'avdmanager create avd -n ACE_Pixel_API_34_b ' +
        '-k "system-images;android-34;google_apis_playstore;arm64-v8a" -d pixel_7',
    );
  });
});
