/**
 * Seam test for dimagi-internal/ace#1665.
 *
 * `ocs-agent-setup` § Step 5's KB recipe (PDD + inputs + training + app
 * summaries) carried NO file naming the programme's contacts, so the
 * escalation address the composed system prompt tells the bot to use —
 * `ace@dimagi-ai.com` — existed only in the prompt. A value with no
 * retrievable anchor is reproduced from prompt recall, and retrieval cannot
 * correct it when it drifts: on `hh-poverty-targeting/20260824-1404`
 * (experiment 13014, collection 566) a 73-prompt deep run emitted
 * `ace@dimagi.com` twice and a wholly invented `pm@dimagi-ai.com` once. Under
 * `ocs-chatbot-eval` § `fabricated_operational_specifics` each clamps to Fail.
 *
 * The invariant: the documented KB recipe must generate and index a contacts
 * file, that file's spec must source the address from `config/agent.json`
 * rather than from prose, unsourced rows must be omitted rather than invented
 * (CLAUDE.md § No inferred backstory), and the composed prompt must POINT at
 * the file instead of restating the address inline.
 *
 * Sibling of `kb-instrument-contamination.test.ts` (ace#1018), which pins the
 * opposite direction of the same recipe — what must NOT be indexed.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));

const agentSetup = readFileSync(`${ROOT}skills/ocs-agent-setup/SKILL.md`, 'utf8');
const goldenTemplate = readFileSync(`${ROOT}scripts/bootstrap-ocs-golden-template.ts`, 'utf8');
const agentConfig = JSON.parse(readFileSync(`${ROOT}config/agent.json`, 'utf8')) as {
  email: string;
};

const CONTACTS_FILE = '00-program-contacts.md';

/**
 * The Step-5 KB recipe: the "Files to gather" list `ocs-agent-setup` uploads
 * into the bot's collection. Same slice the ace#1018 sibling reads, so the two
 * tests agree on what "the recipe" is.
 */
function kbRecipeFileList(md: string): string {
  const start = md.indexOf('Files to gather:');
  expect(start, 'ocs-agent-setup Step 5 must still carry a "Files to gather:" list').toBeGreaterThan(
    -1,
  );
  const rest = md.slice(start);
  // Stop at the prose that follows the list — including the contacts file's own
  // spec block, so a mention THERE can never stand in for a recipe entry.
  const end = Math.min(
    ...['For each file, base64-encode', 'The generated contacts file']
      .map((marker) => rest.indexOf(marker))
      .filter((i) => i !== -1),
  );
  return Number.isFinite(end) ? rest.slice(0, end) : rest;
}

/** The bullet entries of the recipe list, one per gathered file. */
function kbRecipeEntries(md: string): string[] {
  return kbRecipeFileList(md)
    .split('\n')
    .filter((l) => /^\s{2,3}- /.test(l))
    .map((l) => l.trim());
}

/** Step 7's system-prompt checklist — from its heading to Step 8's. */
function composedPromptChecklist(md: string): string {
  const start = md.indexOf('7. **Compose the system prompt**');
  expect(start, 'ocs-agent-setup must still carry Step 7 (Compose the system prompt)').toBeGreaterThan(
    -1,
  );
  const rest = md.slice(start);
  const end = rest.indexOf('8. **Patch the chatbot');
  return end === -1 ? rest : rest.slice(0, end);
}

describe('ocs-agent-setup KB recipe carries the programme contacts (ace#1665)', () => {
  it('the "Files to gather" list names the generated contacts file', () => {
    expect(
      kbRecipeEntries(agentSetup).some((entry) => entry.includes(CONTACTS_FILE)),
      `ocs-agent-setup's "Files to gather" list does not name ${CONTACTS_FILE}. ` +
        `Without it the escalation address has no retrievable anchor in the ` +
        `collection, so the bot reproduces it from prompt recall and retrieval ` +
        `cannot correct the drift (ace#1665).`,
    ).toBe(true);
  });

  it('the contacts file is specified as generated, not read from Drive', () => {
    // Every other recipe entry is copied out of Drive. If this one is written
    // as a Drive path, the step is unrunnable — nothing upstream produces it.
    const recipe = kbRecipeFileList(agentSetup);
    expect(recipe).toMatch(/GENERATED BY THIS STEP/);
    expect(recipe).not.toMatch(new RegExp(`runs/<run-id>/[\\w-]*/${CONTACTS_FILE}`));
  });

  it('the file spec sources the escalation address from config/agent.json', () => {
    // The address must be read from the identity file, not typed from memory
    // into a skill doc that then becomes its own (drifting) source of truth.
    expect(agentSetup).toMatch(/`config\/agent\.json`\s*(?:→|->)\s*`?email`?/);
    expect(agentConfig.email).toBe('ace@dimagi-ai.com');
    expect(
      agentSetup.includes(agentConfig.email),
      `the contacts-file spec must show the canonical address (${agentConfig.email}) ` +
        `in its expected shape so the generated page is checkable.`,
    ).toBe(true);
  });

  it('the spec requires unsourced rows to be OMITTED, not filled in', () => {
    // CLAUDE.md § No inferred backstory: Phase 5 normally runs before Phase 8,
    // so selected_llo is usually absent. A placeholder on a retrievable page is
    // worse than a missing row — the bot hands an operator something to act on.
    const spec = agentSetup.slice(agentSetup.indexOf('The generated contacts file'));
    expect(spec).toMatch(/omitted/i);
    expect(spec).toMatch(/No inferred backstory/);
    expect(spec).toMatch(/selected_llo\.contact_email/);
  });

  it('the composed prompt points at the contacts file instead of restating the address', () => {
    const step7 = composedPromptChecklist(agentSetup);
    expect(
      step7.includes(CONTACTS_FILE),
      `Step 7 must tell the bot to take the escalation address from ` +
        `${CONTACTS_FILE} so retrieval is the anchor.`,
    ).toBe(true);
    expect(
      step7.includes(agentConfig.email),
      `Step 7 restates ${agentConfig.email} inline in the composed prompt. That is ` +
        `the ace#1665 defect: a prompt-only value is reproduced from recall. Point ` +
        `at ${CONTACTS_FILE} instead.`,
    ).toBe(false);
  });

  it('the ace#1142 anti-fabrication guard still carries the address for cold start', () => {
    // Guards the design, not just the edit: the golden template's inline address
    // is the fallback for the window before the collection is attached and
    // indexed. This test must fail loudly if someone "cleans it up" on the
    // strength of the ace#1665 change.
    expect(goldenTemplate).toContain(agentConfig.email);
    expect(goldenTemplate).toMatch(/not ace@dimagi\.com or any other spelling/);
  });
});
