#!/usr/bin/env npx tsx
/**
 * Regenerates `docs/phase-products-schema.json` — the machine-readable,
 * cross-repo single source of truth for the `run_state.yaml`
 * `phases.<phase>.products.*` typed-handoff contract.
 *
 * Why: the contract is enforced ACE-side at write time (the
 * `update_yaml_file` `validateAs` guard, backed by
 * `lib/phase-products-schema.ts`) but is ALSO consumed by ace-web's public
 * summary page (`apps/opps/summary.py`, Python) and by opp-eval. Two
 * languages, two repos — exactly the setup where a TS schema and a Python
 * reader silently diverge (jjackson/ace#705, and the already-rotted
 * `lib/products-apps-schema.ts` whose nova_url assertion no longer matches
 * deployed ace-web). Emitting one JSON Schema both sides read kills the
 * divergence: ace-web validates/reads against this file, ACE generates it
 * from the Zod definitions, and the staleness gate
 * (`test/scripts/dump-phase-products-schema.test.ts`) fails CI if the
 * committed file drifts from the source.
 *
 * Usage:
 *   npx tsx scripts/dump-phase-products-schema.ts            # write the JSON
 *   npx tsx scripts/dump-phase-products-schema.ts --check    # exit 1 if stale (CI)
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { zodToJsonSchema } from 'zod-to-json-schema';
import {
  PHASE_PRODUCTS_SCHEMAS,
  REQUIRED_PRODUCT_KEYS,
  PRODUCT_PRODUCERS,
  PRODUCT_PRODUCERS_SEMANTICS,
  UNATTRIBUTED_PRODUCT_KEYS,
} from '../lib/phase-products-schema.js';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_PATH = path.join(REPO_ROOT, 'docs', 'phase-products-schema.json');

function build(): string {
  const phases: Record<string, unknown> = {};
  for (const [phase, schema] of Object.entries(PHASE_PRODUCTS_SCHEMAS)) {
    // `productProducers` is the dotted product-key → producing-skill map
    // ace-web's skill fork trims by (ace#2354); `null` (not `{}`) when the
    // phase declares none, so a consumer can keep its carry-all fallback.
    const producers = (PRODUCT_PRODUCERS as Record<string, Record<string, string> | undefined>)[phase];
    phases[phase] = {
      schema: zodToJsonSchema(schema as any, { name: `${phase}-products`, $refStrategy: 'none' }),
      requiredProductKeys: (REQUIRED_PRODUCT_KEYS as Record<string, string[]>)[phase] ?? [],
      productProducers: producers ?? null,
      unattributedProductKeys: (
        UNATTRIBUTED_PRODUCT_KEYS as Record<string, ReadonlyArray<{ key: string; reason: string }> | undefined>
      )[phase] ?? [],
    };
  }
  const doc = {
    _generated:
      'GENERATED by scripts/dump-phase-products-schema.ts from lib/phase-products-schema.ts — do not edit by hand. ' +
      'Single source of truth for run_state.yaml phases.<phase>.products.*; read by ace-web apps/opps/summary.py ' +
      '(schema) and apps/opps/skills.py::product_producers (productProducers, ace#2354).',
    productProducersSemantics: PRODUCT_PRODUCERS_SEMANTICS,
    phases,
  };
  return JSON.stringify(doc, null, 2) + '\n';
}

function main() {
  const check = process.argv.includes('--check');
  const next = build();
  if (check) {
    const current = fs.existsSync(OUT_PATH) ? fs.readFileSync(OUT_PATH, 'utf-8') : '';
    if (current !== next) {
      console.error(
        'docs/phase-products-schema.json is STALE.\n' +
          'Run: npx tsx scripts/dump-phase-products-schema.ts\nand commit the result.',
      );
      process.exit(1);
    }
    console.log('docs/phase-products-schema.json is up to date.');
    return;
  }
  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, next);
  console.log(`Wrote ${path.relative(REPO_ROOT, OUT_PATH)}`);
}

main();
